-- =====================================================================
--  무료 부고장·청첩장 정식판 (2026-10-06) — 표 두 개 + 조회수 함수
--
--  cards          : 내용(data). 짧은 링크 /c/<id>. 수정 키는 해시(edit_hash)만 저장.
--                   기간(부고 발인+7일, 청첩장 예식+30일)이 지나면 크론이 data 를 지우고 closed_at 을 찍는다.
--  card_comments  : 조문 글·축하 방명록. 카드가 닫히면 함께 지운다. ip_hash 는 하루 단위 HMAC(원 IP 저장 안 함).
--                   cards.ip_hash 도 같은 방식 — 도배 막기(만들기 한 시간 12개, 글 10분 5개)에만 쓴다.
--  card_touch(id) : 조회수 +1 (읽고 쓰기 경합 없이).
--  세 가지 모두 service_role(서버 api/order-meta.js) 전용 — 손님 브라우저는 직접 못 읽고 못 쓴다.
--
--  기존 표는 건드리지 않는다. 여러 번 실행해도 된다.
--  Supabase → SQL Editor 에 전체 붙여넣고 Run → 맨 아래 cards_ready = true 면 끝.
--  실행 전에도 사이트는 동작한다(만들기 화면이 예전처럼 긴 링크로 만든다).
-- =====================================================================

create table if not exists public.cards (
  id          text primary key check (id ~ '^[A-Za-z0-9]{6,12}$'),
  kind        text not null check (kind in ('f', 'w')),
  data        jsonb,
  edit_hash   text not null check (edit_hash ~ '^[a-f0-9]{64}$'),
  views       integer not null default 0,
  ip_hash     text,
  expires_at  timestamptz not null,
  closed_at   timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
alter table public.cards add column if not exists ip_hash text;   -- 하루 단위 HMAC(원 IP 저장 안 함) — 한 곳에서 한 시간 12개까지
create index if not exists cards_open_expiry_idx on public.cards(expires_at) where closed_at is null;
create index if not exists cards_ip_idx on public.cards(ip_hash, created_at);

create table if not exists public.card_comments (
  id          bigint generated by default as identity primary key,
  card_id     text not null references public.cards(id) on delete cascade,
  name        text not null check (char_length(name) between 1 and 20),
  body        text not null check (char_length(body) between 1 and 300),
  ip_hash     text,
  hidden      boolean not null default false,
  created_at  timestamptz not null default now()
);
create index if not exists card_comments_card_idx on public.card_comments(card_id, created_at desc);
create index if not exists card_comments_rate_idx on public.card_comments(card_id, ip_hash, created_at);

alter table public.cards enable row level security;
alter table public.card_comments enable row level security;
revoke all on table public.cards from public, anon, authenticated;
revoke all on table public.card_comments from public, anon, authenticated;
grant all on table public.cards to service_role;
grant all on table public.card_comments to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.card_touch(p_id text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.cards set views = views + 1 where id = p_id and closed_at is null;
$$;
revoke all on function public.card_touch(text) from public, anon, authenticated;
grant execute on function public.card_touch(text) to service_role;

-- 확인
select (to_regclass('public.cards') is not null
        and to_regclass('public.card_comments') is not null
        and to_regprocedure('public.card_touch(text)') is not null
        and not has_table_privilege('anon', 'public.cards', 'SELECT')
        and not has_table_privilege('anon', 'public.card_comments', 'INSERT')) as cards_ready;
