-- =====================================================================
--  청첩장 참석 여부 (2026-10-08) — 표 하나
--
--  card_rsvps : 하객이 남긴 참석해요(인원)·못 가요. 카드가 닫히면 함께 지운다. ip_hash 는 하루 단위 HMAC(원 IP 저장 안 함).
--  service_role(서버 api/order-meta.js) 전용 — 손님 브라우저는 직접 못 읽고 못 쓴다.
--  supabase-cards.sql(표 cards) 이 먼저 있어야 한다. 여러 번 실행해도 된다.
--  실행 전에도 사이트는 동작한다(참석 여부 칸만 안 보인다).
--  Supabase → SQL Editor 에 전체 붙여넣고 Run → 맨 아래 rsvp_ready = true 면 끝.
-- =====================================================================

create table if not exists public.card_rsvps (
  id          bigint generated by default as identity primary key,
  card_id     text not null references public.cards(id) on delete cascade,
  name        text not null check (char_length(name) between 1 and 20),
  attend      boolean not null,
  headcount   integer not null default 1 check (headcount between 1 and 10),
  side        text not null default '' check (side in ('', 'groom', 'bride')),
  memo        text not null default '' check (char_length(memo) <= 100),
  ip_hash     text,
  created_at  timestamptz not null default now()
);
create index if not exists card_rsvps_card_idx on public.card_rsvps(card_id, created_at desc);
create index if not exists card_rsvps_rate_idx on public.card_rsvps(card_id, ip_hash, created_at);

alter table public.card_rsvps enable row level security;
revoke all on table public.card_rsvps from public, anon, authenticated;
grant all on table public.card_rsvps to service_role;
grant usage, select on all sequences in schema public to service_role;

-- 확인
select (to_regclass('public.card_rsvps') is not null
        and not has_table_privilege('anon', 'public.card_rsvps', 'SELECT')
        and not has_table_privilege('anon', 'public.card_rsvps', 'INSERT')) as rsvp_ready;
